<<<<<<< HEAD
dependencies:
  - bokeh
  - nbserverproxy
  - pandas
  - numpy
  - fiona
  - geopandas
  - shapely
=======
dependencies:
  - bokeh
  - nbserverproxy
  - pandas
  - numpy
  - fiona
  - geopandas
  - shapely
  - pscript
>>>>>>> 103f0cfb8c15aaf93caed9e561f1ab79d1c88f6d
